service: hilliard-guard-manager-backend
frameworkVersion: "4"
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: ${env:BACKEND_REGION, 'us-east-1'}
  stage: ${env:STAGE, 'prod'}
  memorySize: 256
  timeout: 15
  deploymentBucket:
    name: serverless-deploy-hgm-prod-us-east-1
    blockPublicAccess: true
    serverSideEncryption: AES256
    skipPolicySetup: true 
  environment:
    TABLE: PoolRotation
    DDB_REGION: us-east-2      # <-- must match where the table actually lives
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:Query
            - dynamodb:Scan
          Resource:
            - arn:aws:dynamodb:us-east-2:${aws:accountId}:table/PoolRotation
            - arn:aws:dynamodb:us-east-2:${aws:accountId}:table/PoolRotation/index/*
  httpApi:
    cors:
      allowedOrigins:
        - https://app.hilliardguardmanager.com
        - http://localhost:5173
        - http://localhost:5174
      allowedMethods: [GET, POST, PUT, DELETE, OPTIONS]
      allowedHeaders: [Content-Type, Authorization, X-Requested-With]
      maxAge: 86400
    metrics: true

# ✅ Package only compiled JS (dist) + deps; exclude src/**
package:
  patterns:
    - dist/**            # compiled output
    - node_modules/**    # deps
    - package.json
    - package-lock.json
    - '!src/**'          # exclude TS sources
    - '!.tsbuildinfo'    # ignore TS build info if present

functions:
  api:
    # ✅ Point Lambda to compiled JS
    handler: dist/handlers/app.handler
    events:
      - httpApi:
          path: /
          method: ANY
      - httpApi:
          path: /{proxy+}
          method: ANY

plugins: []   # keep empty; do not use serverless-esbuild with v4
