service: hilliard-guard-manager-backend
frameworkVersion: "4"
useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  region: ${env:BACKEND_REGION, 'us-east-1'}
  stage: ${env:STAGE, 'prod'}
  memorySize: 256
  timeout: 15
  deploymentBucket:
    name: serverless-deploy-hgm-prod-us-east-1
    blockPublicAccess: true
    serverSideEncryption: AES256
    skipPolicySetup: true
  environment:
    TABLE: PoolRotation
    DDB_REGION: us-east-2
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:Query
            - dynamodb:Scan
          Resource:
            - arn:aws:dynamodb:us-east-2:${aws:accountId}:table/PoolRotation
            - arn:aws:dynamodb:us-east-2:${aws:accountId}:table/PoolRotation/index/*
  httpApi:
    cors:
      allowedOrigins:
        - https://app.hilliardguardmanager.com
        - http://localhost:5173
        - http://localhost:5174
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowedHeaders:
        - Content-Type
        - x-api-key
        - x-rotation-instance
        - Cache-Control
        - Pragma
        - Accept
        - Origin
        - X-Requested-With
      allowCredentials: false
      maxAge: 86400
    metrics: true

package:
  patterns:
    - dist/**
    - node_modules/**
    - package.json
    - package-lock.json
    - '!src/**'
    - '!.tsbuildinfo'

functions:
  api:
    handler: dist/handlers/app.handler
    events:
      - httpApi: '*'

plugins: []
